# Generated by Django 3.1.6 on 2021-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordembedded', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
