# Generated by Django 3.1.6 on 2021-02-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordembedded', '0002_cars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.AddField(
            model_name='wordembedded',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
